server:
  port: 8089
  servlet:
    context-path: /scooterweb
  address: localhost
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:DB/scooter.DB
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
